import { formatBytes } from '../utils/bytes.js';
import { EXTENSION_GROUP } from './heuristics.js';
import type { ProposedRule } from './heuristics.js';

/**
 * The text `init` writes.
 *
 * Generated as a string rather than serialized from an object, because the
 * comments are the point. A config with no comments teaches nothing, and the
 * two things people get wrong about this schema - that `kb` is 1024 and that
 * every matching rule applies rather than only the last - are exactly the two
 * things a serializer would drop on the floor.
 *
 * Both templates are validated through the real loader before anything is
 * written, so a change here that produces YAML the parser rejects fails loudly
 * at the point of the bug rather than the next time somebody runs `check`.
 */

const HEADER = [
  '# Rasterwright image policy. Commit this file; `check` and `fix` both read it.',
  '#',
  '# Byte sizes are 1024-based, matching what your file browser shows you:',
  '# 500kb is 512000 bytes and 1mb is 1048576. A plain number is bytes.',
];

const DEFAULTS = [
  '# Applied to every governed image. A matching rule below overrides these',
  '# property by property.',
  'defaults:',
  '  upscale: false # Rasterwright never enlarges an image.',
  '  stripMetadata: true # Drop EXIF/XMP/IPTC when a file is rewritten. ICC is kept.',
  '  autoOrient: true # Normalize a non-normal EXIF orientation flag.',
  '  colorSpace: srgb # Only srgb is supported.',
];

const RULES_PREAMBLE = [
  '# Globs are matched against paths relative to this file, with POSIX slashes.',
  '# EVERY matching rule applies, in the order written here, and a later rule',
  '# wins property by property - so a broad rule followed by a narrow one is the',
  '# way to make an exception. Specificity is not considered; file order is.',
  '#',
  '# A file that no rule matches is ungoverned: Rasterwright counts it and',
  '# otherwise leaves it entirely alone.',
  '#',
  '# Properties not used below: maxHeight, format, and quality. For example:',
  '#   maxHeight: 2000',
  '#   format: webp                      # renames files; `fix` needs --allow-renames',
  '#   quality: { start: 82, floor: 40 } # start is a maximum, never a target',
  'rules:',
];

/**
 * A glob as a single-quoted YAML scalar.
 *
 * Single quotes, not double, because a glob can legitimately contain a
 * backslash: escaping the pattern characters in a directory name puts them
 * there, and a directory can also just be called `a\b`. Inside double quotes
 * YAML would read that backslash as an escape and hand the loader a different
 * pattern than the one that was generated - silently, and only for the
 * directories least likely to be tested. Inside single quotes the only special
 * character is `'` itself, which is written twice.
 */
function quoteGlob(glob: string): string {
  return `'${glob.replace(/'/g, "''")}'`;
}

/** Commented examples repeated under each generated rule, so editing is obvious. */
function ruleFooter(maxWidth: number): string[] {
  return [
    `    # maxHeight: ${maxWidth}`,
    '    # format: webp # renames files; `fix` then needs --allow-renames',
  ];
}

/**
 * The template `--bare` writes, and the fallback when a repo holds no images.
 *
 * The single rule is real rather than commented out because the schema requires
 * at least one: a config whose `rules` block is empty governs nothing, and
 * `parsePolicy` says so rather than accepting a file that quietly does nothing.
 */
export function renderBare(): string {
  const lines = [
    ...HEADER,
    '#',
    '# This is the bare template. Edit the rule below to point at the directory',
    '# your images actually live in, then run `rasterwright check`.',
    '',
    'version: 1',
    '',
    ...DEFAULTS,
    '',
    ...RULES_PREAMBLE,
    `  ${quoteGlob(`assets/**/${EXTENSION_GROUP}`)}:`,
    '    maxWidth: 2400',
    '    maxBytes: 500kb',
    ...ruleFooter(2400),
  ];

  return `${lines.join('\n')}\n`;
}

export interface ScanSummary {
  /** Images the scan measured. */
  scanned: number;
  /** Images no generated rule governs. */
  ungoverned: number;
}

/** The template written after a scan, one rule per anchor with its provenance. */
export function renderScanned(rules: readonly ProposedRule[], summary: ScanSummary): string {
  const lines = [
    ...HEADER,
    '#',
    `# Generated by \`rasterwright init\` from the ${count(summary.scanned, 'image')} it found`,
    '# in this repository. The numbers below describe what is already here,',
    '# rounded up so most of it passes today. Edit them to describe what you want.',
    '',
    'version: 1',
    '',
    ...DEFAULTS,
    '',
    ...RULES_PREAMBLE,
  ];

  for (const [index, rule] of rules.entries()) {
    if (index > 0) lines.push('');
    lines.push(`  # ${provenanceFor(rule)}`);
    lines.push(`  ${quoteGlob(rule.glob)}:`);
    lines.push(`    maxWidth: ${rule.maxWidth}`);
    lines.push(`    maxBytes: ${rule.maxBytes.label}`);
    lines.push(...ruleFooter(rule.maxWidth));
  }

  if (summary.ungoverned > 0) {
    lines.push('');
    lines.push(`  # Not covered by any rule above: ${count(summary.ungoverned, 'image')}.`);
    lines.push('  # Rasterwright counts ungoverned files and otherwise leaves them alone.');
    lines.push('  # Add a glob here if you want them governed.');
  }

  return `${lines.join('\n')}\n`;
}

/** The comment above a rule: where its numbers came from, in one line. */
function provenanceFor(rule: ProposedRule): string {
  return (
    `${count(rule.stats.measured, 'image')}. ` +
    `Widths up to ${rule.stats.widestSeen} (90th percentile ${rule.stats.p90Width}); ` +
    `sizes up to ${formatBytes(rule.stats.largestSeen)} (95th percentile ${formatBytes(rule.stats.p95Bytes)}).`
  );
}

function count(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}
