import { describe, expect, it } from 'vitest';

import { parseConfigText } from '../../src/config/load.js';
import { BUILT_IN_DEFAULTS } from '../../src/config/schema.js';
import { anchorsFor, BYTE_LADDER, proposeRules } from '../../src/init/heuristics.js';
import { renderBare, renderScanned } from '../../src/init/template.js';
import type { ProposedRule } from '../../src/init/heuristics.js';
import type { ImageInfo } from '../../src/types.js';

function image(path: string, overrides: Partial<ImageInfo> = {}): ImageInfo {
  return {
    path,
    bytes: 10_000,
    format: 'jpeg',
    width: 800,
    height: 600,
    storedWidth: 800,
    storedHeight: 600,
    hasAlpha: false,
    isOpaque: null,
    bitDepth: 8,
    pixelColorSpace: 'srgb',
    colorSpaceStatus: 'srgb',
    hasIccProfile: false,
    iccDescription: null,
    hasExif: false,
    hasXmp: false,
    hasIptc: false,
    hasOtherMetadata: false,
    orientation: 1,
    isAnimated: false,
    contentHash: 'a'.repeat(64),
    ...overrides,
  };
}

function rulesFor(dirs: Record<string, number>): ProposedRule[] {
  const paths: string[] = [];
  for (const [dir, n] of Object.entries(dirs)) {
    for (let index = 0; index < n; index += 1) paths.push(`${dir}/f${index}.jpg`);
  }
  const infos = new Map(paths.map((path, index) => [path, image(path, { width: 700 + index, bytes: 50_000 + index })]));
  return proposeRules(anchorsFor(paths), infos);
}

describe('the bare template', () => {
  const text = renderBare();

  it('loads through the real config parser', () => {
    expect(() => parseConfigText(text, '<test>')).not.toThrow();
  });

  it('writes the built-in defaults out explicitly', () => {
    expect(parseConfigText(text, '<test>').defaults).toEqual(BUILT_IN_DEFAULTS);
  });

  it('declares exactly one real rule, because the schema requires one', () => {
    const policy = parseConfigText(text, '<test>');
    expect(policy.rules).toHaveLength(1);
    expect(policy.rules[0]?.body.maxWidth).toBe(2400);
    expect(policy.rules[0]?.body.maxBytes).toBe(512_000);
  });

  it('never emits format or maxHeight as live properties', () => {
    for (const rule of parseConfigText(text, '<test>').rules) {
      expect(rule.body.format).toBeUndefined();
      expect(rule.body.maxHeight).toBeUndefined();
    }
  });

  it('explains that kb is 1024, and how rules combine', () => {
    expect(text).toContain('1024-based');
    expect(text).toContain('512000 bytes');
    expect(text).toContain('a later rule');
    expect(text).toContain('ungoverned');
  });

  it('offers maxHeight, format and quality as commented examples', () => {
    expect(text).toContain('# maxHeight:');
    expect(text).toContain('#   format: webp');
    expect(text).toContain('#   quality: { start: 82, floor: 40 }');
  });

  it('ends with exactly one newline', () => {
    expect(text.endsWith('\n')).toBe(true);
    expect(text.endsWith('\n\n')).toBe(false);
  });

  it('is byte-identical every time it is rendered', () => {
    expect(renderBare()).toBe(text);
  });
});

describe('the scanned template', () => {
  it('round-trips one rule through the parser with the numbers it was given', () => {
    const rules = rulesFor({ 'assets/images': 5 });
    const policy = parseConfigText(renderScanned(rules, { scanned: 5, ungoverned: 0 }), '<test>');

    expect(policy.rules).toHaveLength(1);
    expect(policy.rules[0]?.glob).toBe(rules[0]?.glob);
    expect(policy.rules[0]?.body.maxWidth).toBe(rules[0]?.maxWidth);
    expect(policy.rules[0]?.body.maxBytes).toBe(rules[0]?.maxBytes.bytes);
  });

  it('round-trips three rules in file order', () => {
    const rules = rulesFor({ a: 4, b: 4, c: 4 });
    const policy = parseConfigText(renderScanned(rules, { scanned: 12, ungoverned: 0 }), '<test>');

    expect(policy.rules.map((rule) => rule.glob)).toEqual(rules.map((rule) => rule.glob));
  });

  it('writes byte limits as ladder labels, not raw byte counts', () => {
    const rules = rulesFor({ assets: 5 });
    const text = renderScanned(rules, { scanned: 5, ungoverned: 0 });
    expect(text).toMatch(/maxBytes: \d+(\.\d+)?(kb|mb)\n/);
  });

  it('every ladder label survives a round trip through the parser', () => {
    const [base] = rulesFor({ assets: 5 });
    for (const rung of BYTE_LADDER) {
      const text = renderScanned([{ ...base!, maxBytes: rung }], { scanned: 5, ungoverned: 0 });
      expect(parseConfigText(text, '<test>').rules[0]?.body.maxBytes).toBe(rung.bytes);
    }
  });

  it('says where the numbers came from, above each rule', () => {
    const rules = rulesFor({ assets: 5 });
    const text = renderScanned(rules, { scanned: 6, ungoverned: 1 });
    expect(text).toContain('90th percentile');
    expect(text).toContain('95th percentile');
    expect(text).toContain('Generated by `rasterwright init`');
    expect(text).toContain('6 images');
  });

  it('mentions ungoverned files only when there are some', () => {
    const rules = rulesFor({ assets: 5 });
    expect(renderScanned(rules, { scanned: 5, ungoverned: 0 })).not.toContain('Not covered by any rule');
    expect(renderScanned(rules, { scanned: 6, ungoverned: 1 })).toContain('Not covered by any rule above: 1 image.');
  });

  it('writes the same defaults as the bare template', () => {
    const rules = rulesFor({ assets: 5 });
    const policy = parseConfigText(renderScanned(rules, { scanned: 5, ungoverned: 0 }), '<test>');
    expect(policy.defaults).toEqual(BUILT_IN_DEFAULTS);
  });

  it('never emits format or maxHeight as live properties', () => {
    const rules = rulesFor({ a: 4, b: 4, c: 4 });
    for (const rule of parseConfigText(renderScanned(rules, { scanned: 12, ungoverned: 0 }), '<test>').rules) {
      expect(rule.body.format).toBeUndefined();
      expect(rule.body.maxHeight).toBeUndefined();
    }
  });

  it('quotes globs, so a brace group is never read as YAML flow syntax', () => {
    const rules = rulesFor({ assets: 5 });
    expect(renderScanned(rules, { scanned: 5, ungoverned: 0 })).toContain(`  '${rules[0]!.glob}':`);
  });
});

describe('globs survive YAML for awkward directory names', () => {
  // Single-quoted scalars, because escaping pattern characters puts backslashes
  // in the glob and double quotes would read those as YAML escapes.
  const NAMES = [
    'img (old)',
    'a(b',
    '{a,b}',
    'a\\b',
    'say "hi"',
    "it's mine",
    '[a]',
    'plus+x',
    '@scope',
    '!neg',
    'uni café',
    'a#b',
    'star*x',
    'q?x',
    'pipe|x',
    'trailing ',
  ];

  it.each(NAMES)('round-trips %j through the config parser unchanged', (name) => {
    const rules = rulesFor({ [name]: 4 });
    expect(rules).toHaveLength(1);

    const text = renderScanned(rules, { scanned: 4, ungoverned: 0 });
    const policy = parseConfigText(text, '<test>');

    expect(policy.rules).toHaveLength(1);
    expect(policy.rules[0]?.glob).toBe(rules[0]?.glob);
  });

  it('doubles a single quote rather than ending the scalar early', () => {
    const rules = rulesFor({ "it's": 4 });
    expect(renderScanned(rules, { scanned: 4, ungoverned: 0 })).toContain("''");
  });

  it('keeps a backslash intact, which double quotes would have eaten', () => {
    const rules = rulesFor({ 'a\\b': 4 });
    const policy = parseConfigText(renderScanned(rules, { scanned: 4, ungoverned: 0 }), '<test>');
    expect(policy.rules[0]?.glob).toContain('\\');
  });
});
